

data:
  root: "data/raw/mortgage_data"
  quarters: ["2008Q1","2008Q2","2008Q3","2008Q4",
             "2009Q1","2009Q2","2009Q3","2009Q4",
             "2010Q1","2010Q2","2010Q3","2010Q4",
             "2011Q1","2011Q2","2011Q3","2011Q4",
             "2012Q1","2012Q2","2012Q3","2012Q4",
             "2013Q1","2013Q2","2013Q3","2013Q4",
             "2014Q1","2014Q2","2014Q3","2014Q4",
             "2015Q1","2015Q2","2015Q3","2015Q4",
             "2016Q1","2016Q2","2016Q3","2016Q4",
             "2017Q1","2017Q2","2017Q3","2017Q4",
             "2018Q1","2018Q2","2018Q3","2018Q4",
             "2019Q1","2019Q2","2019Q3","2019Q4",
             "2020Q1","2020Q2","2020Q3","2020Q4",
             "2021Q1","2021Q2","2021Q3","2021Q4",
             "2022Q1","2022Q2","2022Q3","2022Q4",
             "2023Q1","2023Q2","2023Q3","2023Q4"]

labels:
  window_months: 12
  delinquency_threshold: 3
  liquidation_codes: ["02","03","09"]
  include_ra: true
  require_full_window: false          
  vintage_basis: origination_quarter

output:
  dir: "data/processed/default_labels"
  format: "parquet"

splits:
  mode: explicit
  explicit:
    design_quarters: ["2008Q1","2008Q2","2008Q3","2008Q4",
                      "2009Q1","2009Q2","2009Q3","2009Q4",
                      "2010Q1","2010Q2","2010Q3","2010Q4",
                      "2011Q1","2011Q2","2011Q3","2011Q4",
                      "2012Q1","2012Q2","2012Q3","2012Q4",
                      "2013Q1","2013Q2","2013Q3","2013Q4",
                      "2014Q1","2014Q2","2014Q3","2014Q4",
                      "2015Q1","2015Q2","2015Q3","2015Q4",
                      "2016Q1","2016Q2","2016Q3","2016Q4",
                      "2017Q1","2017Q2","2017Q3","2017Q4",
                      "2018Q1","2018Q2","2018Q3","2018Q4",
                      "2019Q1","2019Q2","2019Q3","2019Q4",
                      "2020Q1","2020Q2","2020Q3","2020Q4",
                      "2021Q1","2021Q2","2021Q3","2021Q4"]
    
    validation_quarters: ["2020Q1","2020Q2","2020Q3","2020Q4",
                          "2021Q1","2021Q2","2021Q3","2021Q4"]

    oos_quarters: ["2022Q1","2022Q2","2022Q3","2022Q4",
                   "2023Q1","2023Q2","2023Q3","2023Q4"]



# data:
#   root: "data/raw/mortgage_data"
#   quarters: ["2014Q1","2014Q2","2014Q3","2014Q4",
#             "2015Q1","2015Q2","2015Q3","2015Q4",
#             "2016Q1","2016Q2","2016Q3","2016Q4",
#             "2017Q1","2017Q2","2017Q3","2017Q4",
#             "2018Q1","2018Q2","2018Q3","2018Q4",
#             "2019Q1","2019Q2","2019Q3","2019Q4",
#             "2020Q1","2020Q2","2020Q3","2020Q4",
#             "2021Q1","2021Q2","2021Q3","2021Q4",
#             "2022Q1","2022Q2","2022Q3","2022Q4",
#             "2023Q1","2023Q2","2023Q3","2023Q4",
#             "2024Q1","2024Q2","2024Q3","2024Q4"]

# labels:
#   window_months: 24
#   delinquency_threshold: 3
#   liquidation_codes: ["02","03","09"]
#   include_ra: true
#   require_full_window: false
#   vintage_basis: origination_quarter

# output:
#   dir: "data/processed/default_labels"
#   format: "parquet"

# # IMPORTANT : on utilise "validation_quarters" (cl√© attendue par impute_and_save.py)
# splits:
#   mode: explicit
#   explicit:
#     design_quarters: ["2014Q1","2014Q2","2014Q3","2014Q4",
#             "2015Q1","2015Q2","2015Q3","2015Q4",
#             "2016Q1","2016Q2","2016Q3","2016Q4",
#             "2017Q1","2017Q2","2017Q3","2017Q4",
#             "2018Q1","2018Q2","2018Q3","2018Q4",
#             "2019Q1","2019Q2","2019Q3","2019Q4",
#             "2020Q1","2020Q2","2020Q3","2020Q4",
#             "2021Q1","2021Q2","2021Q3","2021Q4",
#             "2022Q1","2022Q2","2022Q3","2022Q4"]
#     validation_quarters: ["2021Q1","2021Q2","2021Q3","2021Q4",
#             "2022Q1","2022Q2","2022Q3","2022Q4"]
#     oos_quarters: ["2023Q1","2023Q2","2023Q3","2023Q4",
#                   "2024Q1","2024Q2","2024Q3","2024Q4"]




# # quarters:   ["2014Q1","2014Q2","2014Q3","2014Q4",
#   #            "2015Q1","2015Q2","2015Q3","2015Q4",
#   #            "2016Q1","2016Q2","2016Q3","2016Q4",
#   #            "2017Q1","2017Q2","2017Q3","2017Q4",
#   #            "2018Q1","2018Q2","2018Q3","2018Q4",
#   #            "2019Q1","2019Q2","2019Q3","2019Q4",
#   #            "2020Q1","2020Q2","2020Q3","2020Q4",
#   #            "2021Q1","2021Q2","2021Q3","2021Q4",
#   #            "2022Q1","2022Q2","2022Q3","2022Q4",
#   #            "2023Q1","2023Q2","2023Q3","2023Q4",
#   #            "2024Q1","2024Q2","2024Q3","2024Q4"]